drome_name: Lovedrome
drome_tagline: People we admire a.k.a. people we love
emoji: smiley
entry_name: Target
entry_description: nickname of <strong>someone you'd like to have near you</strong> lots of days.
living_things_drome: true
