environment_vars:
  gmail_username: GMAIL_USERNAME
  gmail_password: GMAIL_PASSWORD
  stream_actor: STREAM_ACTOR
  stream_key: STREAM_KEY
  stream_secret: STREAM_SECRET
  twitter_key: CONSUMER_KEY
  twitter_secret: CONSUMER_SECRET
  neo4j_server: NEO4J_SERVER
  neo4j_username: NEO4J_USERNAME
  neo4j_password: NEO4J_PASSWORD
# gmail:
#   username: nando
#   password: odnan
#   from: myselfhone@example.com
#   subject_prefix: dromo
